name: Generate site and push to Github Pages

on:
  push:
    branches:
      - deploy
      - 1-test-setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install lektor
      - name: Create output directory for Lektor
        run: mkdir -p output
      - name: Build site to output directory
        run: lektor build --output-path ./output
